name: Test

on:
  pull_request:
  push:
    branches: [main, dev]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - run: go test ./...
      - run: go test -race ./...
      - run: go vet ./...
      - run: go run golang.org/x/vuln/cmd/govulncheck@v1.7.0 ./...

  windows-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - run: make build-windows-artifact
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ppvpn-core-windows-${{ github.sha }}
          path: |
            build/ppvpn-core-windows-amd64.exe
            build/ppvpn-core-windows-arm64.exe
            build/windows-SHA256SUMS

  apple-artifacts:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - run: make bootstrap-mobile
      - run: make build-macos-artifact build-ios-artifact
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ppvpn-core-apple-${{ github.sha }}
          path: |
            build/PPVPNCore.xcframework
            build/PPVPNCore.xcframework.zip
            build/macos-SHA256SUMS
            build/ios-SHA256SUMS

  android-artifact:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.0.0
        with:
          distribution: temurin
          java-version: '17'
      - run: make bootstrap-mobile
      - run: make build-android-artifact
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ppvpn-core-android-${{ github.sha }}
          path: |
            build/ppvpn-core.aar
            build/android-SHA256SUMS
